name: Auto Sync

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour
  workflow_dispatch: {}   # allows manual run

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Auto Sync
        uses: CrankAddict/auto-sync@v1
        with:
          config_path: .github/auto-sync.json
